#!/bin/bash -v

# This script runs on instances with a node_type tag of "kafka"
# It sets the roles that determine what software is installed
# on this instance by platform-salt scripts and the minion
# id and hostname

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

# Parameters:
#  $1 - node index for this kafka node - as this node type may be horizontally scaled, should start at 0.

set -e

cat >> /etc/salt/grains <<EOF
roles:
  - zookeeper
  - kafka
EOF

if [ $1 = 0 ]; then
cat >> /etc/salt/grains <<EOF
  - platform_testing_general
  - kafka_manager
  - elk
  - kafka_tool
EOF
fi

cat >> /etc/salt/grains <<EOF
cluster: zk$PNDA_CLUSTER
broker_id: $1
EOF

cat >> /etc/salt/minion <<EOF
id: $PNDA_CLUSTER-kafka-$1
EOF

cat >> /etc/salt/grains <<EOF
vlans:
  internal: eth0
  producer: eth1
  interfaces: eth0
EOF

DISTRO=$(cat /etc/*-release|grep ^ID\=|awk -F\= {'print $2'}|sed s/\"//g)
if [ "x$DISTRO" == "xubuntu" ]; then

cat > /etc/network/interfaces.d/eth1.cfg <<EOF
auto eth1
iface eth1 inet dhcp
EOF

ifup eth1

elif [ "x$DISTRO" == "xrhel" ]; then

cat > /etc/sysconfig/network-scripts/ifcfg-eth1 <<EOF
DEVICE="eth1"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
USERCTL="yes"
PEERDNS="yes"
IPV6INIT="no"
EOF

fi

echo $PNDA_CLUSTER-kafka-$1 > /etc/hostname
hostname $PNDA_CLUSTER-kafka-$1

service salt-minion restart
