#!/bin/bash -v

# This script runs on instances with a node_type tag of "opentsdb"
# It sets the roles that determine what software is installed
# on this instance by platform-salt scripts and the minion
# id and hostname

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

# Parameters:
#  $1 - node index for this opentsdb node - as this node type may be horizontally scaled, should start at 0.

set -e

cat >> /etc/salt/grains <<EOF
roles:
  - opentsdb
EOF
if [ $1 = 0 ]; then
cat >> /etc/salt/grains <<EOF
  - grafana
EOF
fi

cat >> /etc/salt/minion <<EOF
id: $PNDA_CLUSTER-opentsdb-$1
EOF

cat >> /etc/salt/minion.d/beacons.conf <<EOF
  service_opentsdb:
    interval: $PLATFORM_SALT_BEACON_TIMEOUT
    disable_during_state_run: True
EOF
echo $PNDA_CLUSTER-opentsdb-$1 > /etc/hostname
hostname $PNDA_CLUSTER-opentsdb-$1

service salt-minion restart
