#!/bin/bash -v

# This script runs on instances with a node_type tag of "saltmaster"
# The base.sh script does not run on this instance type
# It mounts the disks and installs a salt master

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables
set -ex

echo $PNDA_CLUSTER-saltmaster > /etc/hostname
hostname $PNDA_CLUSTER-saltmaster

service salt-master restart

# Also include a minion on the saltmaster instance
cat >> /etc/salt/minion <<EOF
id: $PNDA_CLUSTER-saltmaster
EOF

service salt-minion restart
