#!/bin/bash -v

# This script runs on instances with a node_type tag of "zk"
# It sets the roles that determine what software is installed
# on this instance by platform-salt scripts and the minion
# id and hostname

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

#  $1 - node index for this zookeeper node - as this node type may be horizontally scaled, should start at 0.

set -e

cat >> /etc/salt/grains <<EOF
roles:
  - zookeeper
cluster: zk$PNDA_CLUSTER
EOF

cat >> /etc/salt/minion <<EOF
id: $PNDA_CLUSTER-zk-$1
EOF

echo $PNDA_CLUSTER-zk-$1 > /etc/hostname
hostname $PNDA_CLUSTER-zk-$1

service salt-minion restart
